/home/ec2-user/eip1559-tx-sender/build/install/chain-filler/bin/chain-filler \
--rpc-endpoints=http://18.222.108.145:8545 \
--num-transactions=5 \
--num-contracts=0 \
--eip-1559-tx-weight=0.5 \
--num-threads=8 \
--fuzz-transfer-value-lower-bound-eth=0.01 \
--fuzz-transfer-value-upper-bound-eth=0.50 \
--filler-mode=scheduler \
--repeat-every-n-seconds=1 \
--genesis-file=/home/ec2-user/genesis.json
