# data
discovery-enabled=false
data-path="/data"
logging="INFO"

# private_key
node-private-key-file="/etc/besu/key"

genesis-file="/etc/besu/genesis.json"
min-gas-price=1000
sync-mode="FULL"
host-whitelist=["*"]



# rpc
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-api=["DEBUG","NET","WEB3","ETH","ADMIN","PERM","MINER","EEA","PRIV","TXPOOL","CLIQUE"]
rpc-http-cors-origins=["all"]


# ws
rpc-ws-enabled=true
rpc-ws-api=["NET","ETH","WEB3"]
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546

# graphql
graphql-http-enabled=true
graphql-http-host="0.0.0.0"
graphql-http-port=8547
graphql-http-cors-origins=["all"]

# p2p
p2p-host="13.236.147.35"
p2p-port=30303

# metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545


# eip1559 testnet
Xeip1559-enabled=true
